#!/bin/sh

remote="$1"
url="$2"

echo "Pycodestyle requirements check before push..."
pycodestyle --config=setup.cfg --statistics .
pycodestyle_exit_code=$?
if [[ $pycodestyle_exit_code == "1" ]]; then
    echo
    echo "There are some failures at Pycodestyle requirements check! Push is not allowed"
    exit 1
fi

echo
echo "All tests are passed!"
echo "Pushing to $remote ($url)"
exit 0
