language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # Run unit tests
  - python -m unittest discover -s tests/ -p "*.py" -v

  # Run codestyle checks
  - cd "$TRAVIS_BUILD_DIR"
  - pep8 --config=setup.cfg --statistics .
