language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # Run dataset checks
  - python tests/dataset_structure.py -v

  # Run codestyle checks
  - pep8 --ignore=E501 "$TRAVIS_BUILD_DIR"
