language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  # pep8 is a mandatory package, it's not required for data processing
  - pip install pep8
script:
  # Run dataset checks
  - python tests/dataset_structure.py -v

  # Run codestyle checks
  - cd "$TRAVIS_BUILD_DIR"
  - find . -type f -name "*.py" -exec pep8 --ignore=E501 {} \;
