name: Python Tests & Codestyle Checks

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests at Python ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.8
          - 3.9
          - 3.10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run test suite
      run: python -m unittest discover -s tests/ -p "*.py" -v
  
  codestyle:
    name: Codestyle Checks
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Code style check
      run: pycodestyle --config=setup.cfg --statistics -v .
